name: CI/CD Pipeline

# El bloque 'on' define los "gatillos" (triggers).
# Le dice a GitHub: "¿CUÁNDO debo ejecutar este flujo?"
on:
  # "Ejecútate cuando alguien suba código (haga push)..."
  push:
    # "...específicamente si lo suben a la rama 'main' o a la rama 'E3-dev'."
    branches:
      - main
      - E3-dev
  # "También ejecútate cuando alguien intente fusionar código (Pull Request) hacia 'main'."
  pull_request:
    branches:
      - main

# El bloque 'jobs' (trabajos) contiene lo que realmente se va a hacer.
jobs:
  # Creamos un trabajo llamado 'test'
  test:
    # Le decimos a GitHub que nos preste una máquina virtual con Ubuntu (Linux) para trabajar.
    runs-on: ubuntu-latest

    # Los 'steps' (pasos) son las instrucciones detalladas para la máquina.
    steps:
      # Paso 1: Clonar/descargar nuestro código desde el repositorio a la máquina virtual.
      - name: Descargar el código
        uses: actions/checkout@v4

      # Paso 2: Instalar la versión de Python que necesitamos (3.10 en este caso).
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Paso 3: Instalar todas las librerías de nuestro proyecto (FastAPI, pytest, etc).
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar nuestras pruebas. 
      # Si fallan, GitHub marca el trabajo con una X roja. Si pasan, con un ✔️ verde.
      - name: Ejecutar pruebas (Pytest)
        # Inyectamos una variable de entorno temporal solo para este paso.
        # Usamos una base de datos SQLite en memoria RAM (sqlite:///:memory:).
        # Así pasamos la validación de inicio sin conectarnos a la BD de producción,
        # lo cual es una excelente práctica para no ensuciar datos reales con tests.
        env:
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          pytest
